name: BST.D${model.config.hidden_size}L${model.config.user_config.num_hidden_layers}
config:
  use_news_content: true
  hidden_size: 64
  neg_count: 4
  news_config:
    flatten: false
    max_pooling: false
  user_config:
    num_attention_heads: 4
    num_hidden_layers: 1
    inputer_config:
      use_cls_token: false
      use_sep_token: false
