name: DCNModel
dir: ${model.name}
config:
  embed_dim: 64
  dnn_hidden_units: [1000, 1000, 1000]
  dnn_dropout: 0.1
  dnn_activations: ReLU
  dnn_batch_norm: false
  cross_num: 3
  columns: ${data.order}$
  columns_doc: ${exp.tasks.0.params.doc_order}$
