name: DCN.D${model.config.hidden_size}
config:
  use_news_content: true
  hidden_size: 768
  dnn_hidden_units: [1000, 1000, 1000]
  dnn_activations: ReLU
  dnn_dropout: 0.1
  dnn_batch_norm: false
  cross_num: 3
  news_config:
    hidden_size: ${model.config.hidden_size}$
    flatten: false
    max_pooling: false
  user_config:
    hidden_size: ${model.config.hidden_size}$
    flatten: false
    max_pooling: false