name: DIN.NRL-D${model.config.hidden_size}
config:
  use_news_content: false
  hidden_size: 768
  dnn_hidden_units: [1000, 1000, 1000]
  dnn_activations: ReLU
  attention_hidden_units: [768]
  attention_dropout: 0.1
  net_dropout: 0.1
  batch_norm: false
  din_use_softmax: false
  user_config:
    inputer_config:
      use_sep_token: false
      use_cls_token: false