name: LLAMA-NRMS.D${model.config.hidden_size}.L${model.config.news_config.layer_split}.Lora${model.config.news_config.lora}
config:
  use_news_content: true
  use_fast_eval: ${fast_eval}$
  max_news_content_batch_size: 0
  same_dim_transform: false
  embed_hidden_size: 4096
  hidden_size: ${hidden_size}$
  neg_count: 4
  news_config:
    hidden_size: ${model.config.hidden_size}$
    llama_dir: /home/qijiong/Code/LLaMA/7B
    layer_split: ${layer}$
    lora: ${lora}$
    weights_dir: data/${data.name}/llama-split
  user_config:
    hidden_size: ${model.config.hidden_size}$
    num_attention_heads: 8
    inputer_config:
      use_cls_token: false
      use_sep_token: false
