name: LSTUR.NRL
config:
  use_news_content: false
  hidden_size: 64
  neg_count: 4
  user_config:
    columns: ${data.news.order}$
    use_news_content: ${model.config.use_news_content}$
    inputer_config:
      use_cls_token: false
      use_sep_token: false
