name: NAML
config:
  use_news_content: true
  hidden_size: 64
  neg_count: 4
  news_config:
    hidden_size: ${model.config.hidden_size}$
    dropout: 0.1
    kernel_size: 3
  user_config:
    hidden_size: ${model.config.hidden_size}$
    inputer_config:
      use_cls_token: false
      use_sep_token: false
