name: NAML-DCN
config:
  use_news_content: true
  hidden_size: 64
  dnn_hidden_units: [1000, 1000, 1000]
  dnn_activations: ReLU
  dnn_dropout: 0.1
  dnn_batch_norm: false
  cross_num: 3
  news_config:
    hidden_size: ${model.config.hidden_size}$
    dropout: 0.1
    kernel_size: 3
  user_config:
    hidden_size: ${model.config.hidden_size}$
    inputer_config:
      use_cls_token: false
      use_sep_token: false
