name: NAML-Fancy-DCN
config:
  use_news_content: true
  hidden_size: 64
  dnn_hidden_units: [1000, 1000, 1000]
  dnn_activations: ReLU
  dnn_dropout: 0.1
  dnn_batch_norm: false
  cross_num: 3
  neg_count: 4
  news_config:
    dropout: 0.1
    kernel_size: 3
  user_config:
    inputer_config:
      use_cls_token: false
      use_sep_token: false
