name: NAML
config:
  use_news_content: true
  use_fast_eval: true
  hidden_size: 64
  neg_count: 4
  news_config:
    dropout: 0.1
    kernel_size: 3
  user_config:
    inputer_config:
      use_cls_token: false
      use_sep_token: false
