name: NRMSModel
dir: ${model.name}
config:
  embed_dim: 300
  doc_encoder_size: 250
  additive_attention_hidden_size: 200
  num_attention_heads: 10
  embedding_dropout: 0.1
  doc_attention_dropout: 0.1
  seq_attention_dropout: 0.1
  user_dropout: 0.2
