name: NRMS
config:
  use_news_content: true
  use_fast_eval: true
  hidden_size: 64
  neg_count: 4
  news_config:
    num_attention_heads: 8
    inputer_config:
      use_cls_token: false
      use_sep_token: true
  user_config:
    num_attention_heads: 8
    inputer_config:
      use_cls_token: false
      use_sep_token: false
