name: NRMS.NRL-D${model.config.hidden_size}
config:
  use_news_content: false
  hidden_size: 768
  neg_count: 4
  user_config:
    hidden_size: ${model.config.hidden_size}$
    num_attention_heads: 12
    inputer_config:
      use_cls_token: false
      use_sep_token: false
