name: PLMNR-BST.D${model.config.hidden_size}
config:
  use_news_content: true
  hidden_size: 768
  neg_count: 4
  news_config:
    hidden_size: ${model.config.hidden_size}$
    num_attention_heads: 12
    num_hidden_layers: 3
    inputer_config:
      use_cls_token: false
      use_sep_token: true
  user_config:
    hidden_size: ${model.config.hidden_size}$
    num_attention_heads: 12
    num_hidden_layers: 3
    inputer_config:
      use_cls_token: false
      use_sep_token: false