name: PLMNR-DIN
config:
  use_news_content: true
  hidden_size: 768
  dnn_hidden_units: [ 1000, 1000, 1000 ]
  dnn_activations: ReLU
  attention_hidden_units: [ 768 ]
  attention_dropout: 0.1
  net_dropout: 0.1
  batch_norm: false
  din_use_softmax: false
  news_config:
    num_attention_heads: 12
    num_hidden_layers: 3
    inputer_config:
      use_cls_token: false
      use_sep_token: true
  user_config:
    num_attention_heads: 12
    inputer_config:
      use_cls_token: false
      use_sep_token: false
