name: PLMNR-DCN
config:
  use_news_content: true
  hidden_size: 768
  dnn_hidden_units: [1000, 1000, 1000]
  dnn_activations: ReLU
  dnn_dropout: 0.1
  dnn_batch_norm: false
  cross_num: 3
  news_config:
    hidden_size: ${model.config.hidden_size}$
    num_attention_heads: 12
    num_hidden_layers: 3
    inputer_config:
      use_cls_token: false
      use_sep_token: true
  user_config:
    hidden_size: ${model.config.hidden_size}$
    flatten: false
    max_pooling: false
