name: ${exp.mode}
dir: saving/${data.name}/${model.name}/${embed.name}-${exp.name}
log: ${exp.dir}/exp.log
mode: test_llama_layer_split
store:
  layers: [31, 30, 28, 24]
  dir: data/${data.name}/llama-split
load:
  save_dir: null
  model_only: true
  strict: true
  wait: false
policy:
  device: gpu
