name: ${exp.tasks.0.name}-${exp.mode}
dir: ${exp.name}/${time.hex}_${rand.4}
mode: test
tasks:
  -
    name: matching-nrl
    params:
      label_col: label
      clicks_col: history
      candidate_col: nid
      neg_count: 4
      use_cls_token: false
      use_sep_token: false
      neg_col: neg
load:
  save_dir: ../../${exp.tasks.0.name}-train/${x}
  epochs: null
  model_only: true
  strict: true
  wait: false
policy:
  freeze_emb: false
  pin_memory: true
  batch_size: 5000
  device: gpu
metrics:
  - LogLoss
  - AUC
  - GAUC
  - MRR
  - F1
  - NDCG@1
  - NDCG@5
  - NDCG@10
  - HitRatio@5
  - HitRatio@10
  - Recall@5
  - Recall@10