name: ${exp.tasks.0.name}-${exp.mode}
dir: ${exp.name}/${time.hex}_${rand.4}
mode: train
tasks:
  -
    name: matching
    params:
      doc_depot: data/${dataset}/news
      doc_order: ['title']
      label_col: label
      clicks_col: history
      candidate_col: nid
      neg_count: 4
      use_cls_token: false
      use_sep_token: false
      neg_col: neg
load:
  save_dir: null
  epochs: null
  model_only: true
  strict: true
  wait: false
store:
#  interval: 10
  monitor: a.loss < b.loss
  top: 1
  early_stop: 2
policy:
  freeze_emb: false
  pin_memory: true
  epoch: 200
  epoch_start: 0
#  lr: 0.001
#  batch_size: 2500
#  accumulate_batch: 1
  lr: 0.0005
  batch_size: 256
  accumulate_batch: 1
  device: gpu
  n_warmup: 0
  check_interval: -2
