name: match
dir: ${exp.name}
model: nrms
mode: train
tasks:
  -
    name: matching
load:
  load_ckpt: null
  load_model_only: true
  relax_load: false
store:
  interval: 10
  super_store: true
  monitor: a.loss < b.loss and a.cluster_loss < b.cluster_loss and a.local_loss < b.local_loss
  top: 5
  epoch_skip: 10
policy:
  freeze_emb: false
  pin_memory: false
  epoch: 200
  epoch_start: 0
  lr: 0.01
  batch_size: 64
  accumulate_batch: 4
  device: gpu
  n_warmup: 600
  check_interval: -2
