name: ${exp.tasks.0.name}-${exp.mode}
dir: ${exp.name}/${time.hex}_${rand.4}
mode: test
tasks:
  -
    name: ranking
    params:
      doc_depot: data/${dataset}/news
      doc_order: ['title']
      label_col: click
      clicks_col: history
      candidate_col: nid
load:
  save_dir: ../../${exp.tasks.0.name}-train/${x}
  epochs: null
  model_only: true
  strict: true
  wait: true
store:
  monitor: a.loss < b.loss
  top: 1
  early_stop: 3
policy:
  freeze_emb: false
  pin_memory: true
  batch_size: 5000
  device: gpu
metrics:
  - LogLoss
  - AUC
  - GAUC
  - MRR
  - F1
  - NDCG@1
  - NDCG@5
  - NDCG@10
  - HitRatio@5
  - HitRatio@10
  - Recall@5
  - Recall@10