name: ${exp.tasks.0.name}-${exp.mode}
dir: ${exp.name}/${time.hex}_${rand.4}
mode: ${mode}
tasks:
  -
    name: ranking
    params:
      doc_depot: data/${dataset}/news
      doc_order: ['title']
      label_col: click
      clicks_col: history
      candidate_col: nid
load:
  save_dir: null
  epochs: null
  model_only: true
  strict: true
  wait: false
store:
  monitor: a.loss < b.loss
  top: 1
  early_stop: 3
policy:
  freeze_emb: false
  pin_memory: true
  epoch: 100
  epoch_start: 0
  lr: 0.001
  batch_size: 5000
  accumulate_batch: 1
  device: gpu
  n_warmup: 0
  check_interval: -2
