name: ${exp.mode}
dir: saving/${data.name}/${model.name}/${embed.name}-${exp.name}
log: ${exp.dir}/exp.log
mode: test
load:
  save_dir: ../${embed.name}-train_test
  epochs: null
  model_only: true
  strict: false
  wait: false
store:
  metric: GAUC
  maximize: true
  top: 1
  early_stop: ${patience}$
policy:
  epoch_start: 0
  epoch: 50
  freeze_emb: false
  pin_memory: false
  epoch_batch: ${epoch_batch}$
  batch_size: ${batch_size}$
  accumulate_batch: ${acc_batch}$
  device: gpu
  n_warmup: ${warmup}$
  check_interval: -2
  simple_dev: ${simple_dev}$
metrics:
  - GAUC
  - MRR
  - NDCG@1
  - NDCG@5
  - NDCG@10