name: ${exp.mode}
dir: saving/${data.name}/${model.name}/${embed.name}-${exp.name}
log: ${exp.dir}/exp.log
mode: test_fake
load:
  save_dir: ../${embed.name}-train_test
  epochs: "[${epoch}]"
  model_only: true
  strict: true
  wait: false
policy:
  pin_memory: false
  batch_size: 200
  device: gpu
metrics:
  - GAUC
  - MRR
  - NDCG@5
  - NDCG@10