name: ${exp.mode}
dir: saving/${data.name}/${model.name}/${embed.name}-${exp.name}
log: ${exp.dir}/exp.log
mode: train_test
load:
  save_dir: null
  epochs: null
  model_only: true
  strict: true
  wait: false
store:
#  metric: GAUC
#  maximize: true
  top: 1
  early_stop: 2
policy:
  epoch_start: 0
  epoch: 50
  lr: 0.0005
  freeze_emb: false
  pin_memory: false
  batch_size: 200
  device: gpu
  n_warmup: 0
  check_interval: -2
  simple_dev: true
metrics:
  - GAUC
  - MRR
  - NDCG@5
  - NDCG@10