name: ${exp.mode}
dir: saving/${data.name}/${model.name}/${embed.name}-${exp.name}
log: ${exp.dir}/exp.log
mode: train_test
load:
  save_dir: null
  epochs: null
  model_only: true
  strict: false
  wait: false
store:
  metric: GAUC
  maximize: true
  top: 1
  early_stop: 5
policy:
  epoch_start: 0
  epoch: 50
  lr: 0.0005
  freeze_emb: false
  pin_memory: false
  batch_size: 128
  device: gpu
  n_warmup: 0
  epoch_batch: ${epoch_batch}$
  check_interval: -2
metrics:
  - GAUC
  - MRR
  - NDCG@1
  - NDCG@5
  - NDCG@10